app/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the Closure to execute when that URI is requested.
  |
 */

// Confide routes
Route::get('users/create', 'UsersController@create');
Route::post('users', 'UsersController@store');
Route::get('admin/login', 'UsersController@login');
Route::post('users/login', 'UsersController@doLogin');
Route::get('users/confirm/{code}', 'UsersController@confirm');
Route::get('users/forgot_password', 'UsersController@forgotPassword');
Route::post('users/forgot_password', 'UsersController@doForgotPassword');
Route::get('users/reset_password/{token}', 'UsersController@resetPassword');
Route::post('users/reset_password', 'UsersController@doResetPassword');
Route::get('admin/logout', ['as' => 'admin.logout', 'uses' => 'UsersController@logout']);

Route::group(['before' => 'auth'], function () {
    Route::get('admin/hot-manga', ['as' => 'admin.manga.hot', 'uses' => 'MangaController@hotManga']);
    Route::post('autoMangaInfo', ['as' => 'admin.manga.autoMangaInfo', 'uses' => 'MangaController@autoMangaInfo']);
    Route::post('updateHotManga', 'MangaController@updateHotManga');
	
    Route::get('admin/options-manga', ['as' => 'admin.manga.options', 'uses' => 'MangaController@mangaOptions']);
    Route::post('saveMangaOptions', ['as' => 'admin.manga.options.save', 'uses' => 'MangaController@saveMangaOptions']);
    Route::get('admin/filterMangaList', 'MangaController@filterList');
    Route::resource('admin/manga', 'MangaController');
    
    Route::get('admin/manga/{manga}/chapter/scraper', ['as' => 'admin.manga.chapter.scraper', 'uses' => 'WebScraperController@scraper']);
    Route::post('startScraper', 'WebScraperController@startScraper');
    Route::post('getTotalChapters', 'WebScraperController@getTotalChapters');
    Route::post('getChapter', 'WebScraperController@getChapter');
    Route::post('abort', 'WebScraperController@abort');
    Route::post('resume', 'WebScraperController@resume');

    
    Route::delete('admin/destroyChapters/{mangaId}', ['as' => 'admin.manga.chapter.destroyChapters', 'uses' => 'ChapterController@destroyChapters']);
    Route::post('notifyUsers', 'ChapterController@notifyUsers');
    Route::resource('admin/manga.chapter', 'ChapterController');

    Route::delete('admin/destroyPages/{mangaId}/{chapterId}', ['as' => 'admin.manga.chapter.page.destroyPages', 'uses' => 'PageController@destroyPages']);
    Route::post('downloadImageFromUrl', 'PageController@downloadImageFromUrl');
    Route::post('uploadZIPFile', 'PageController@uploadZIPFile');
    Route::post('createExternalPages', 'PageController@createExternalPages');
    Route::post('movePage', 'PageController@movePage');
    Route::resource('admin/manga.chapter.page', 'PageController');

    Route::resource('admin/category', 'CategoryController');

    // CKeditor upload image
    Route::post('admin/uploadPostImage', ['as' => 'admin.posts.uploadImage', 'uses' => 'PostController@uploadImage']);
    Route::get('admin/uploadBrowseImage', ['as' => 'admin.posts.browseImage', 'uses' => 'PostController@browseImage']);
    Route::post('admin/deletePostImage', ['as' => 'admin.posts.deletePostImage', 'uses' => 'PostController@deletePostImage']);

    Route::resource('admin/comictype', 'ComicTypeController');
    Route::resource('admin/posts', 'PostController');

    // Settings
    Route::get('admin/general', ['as' => 'admin.settings.general', 'uses' => 'SettingsController@general']);
    Route::post('admin/general', ['as' => 'admin.settings.general.save', 'uses' => 'SettingsController@saveGeneral']);

    Route::get('admin/seo', ['as' => 'admin.settings.seo', 'uses' => 'SettingsController@seo']);
    Route::post('admin/seo', ['as' => 'admin.settings.seo.save', 'uses' => 'SettingsController@saveSeo']);

    Route::get('admin/profile', ['as' => 'admin.settings.profile', 'uses' => 'SettingsController@profile']);
    Route::post('admin/profile', ['as' => 'admin.settings.profile.save', 'uses' => 'SettingsController@saveProfile']);

    Route::get('admin/theme', ['as' => 'admin.settings.theme', 'uses' => 'SettingsController@theme']);
    Route::post('admin/theme', ['as' => 'admin.settings.theme.save', 'uses' => 'SettingsController@saveTheme']);

    Route::get('admin/widgets', ['as' => 'admin.settings.widgets', 'uses' => 'SettingsController@widgets']);
    Route::post('admin/widgets', ['as' => 'admin.settings.widgets.save', 'uses' => 'SettingsController@saveWidgets']);

    Route::get('admin/cache', ['as' => 'admin.settings.cache', 'uses' => 'SettingsController@cache']);
    Route::post('admin/cache', ['as' => 'admin.settings.cache.save', 'uses' => 'SettingsController@saveCache']);
    Route::post('admin/clear-cache', ['as' => 'admin.settings.cache.clear', 'uses' => 'SettingsController@clearCache']);
    Route::post('admin/clear-downloads', ['as' => 'admin.settings.downloads.clear', 'uses' => 'SettingsController@clearDownloads']);

    // Google
    Route::get('admin/gdrive', ['as' => 'admin.settings.gdrive', 'uses' => 'Cyberziko\Gdrive\Controllers\GoogleController@index']);
    Route::post('admin/gdrive/reset', ['as' => 'admin.settings.gdrive.reset', 'uses' => 'Cyberziko\Gdrive\Controllers\GoogleController@resetGdrive']);
    Route::post('admin/gdrive', ['as' => 'admin.settings.gdrive.save', 'uses' => 'Cyberziko\Gdrive\Controllers\GoogleController@saveGdrive']);

    Route::post('saveSubscription', ['as' => 'admin.users.subsciption', 'uses' => 'ManageUserController@saveSubscription']);
    Route::get('admin/permissions', ['as' => 'admin.users.permissions', 'uses' => 'ManageUserController@permissions']);
    Route::resource('admin/role', 'RoleController');
    Route::resource('admin/user', 'ManageUserController');

    Route::post('uploadMangaCover', 'FileUploadController@uploadMangaCover');
    Route::post('uploadMangaChapterPage', 'FileUploadController@uploadMangaChapterPage');
    Route::post('deleteImage', 'FileUploadController@deleteImage');
    Route::post('deleteCover', 'FileUploadController@deleteCover');
    Route::post('uploadAvatar', 'FileUploadController@uploadAvatar');
    Route::post('deleteAvatar', 'FileUploadController@deleteAvatar');

    Route::post('admin/ads/storePlacements', ['as' => 'admin.ads.storePlacements', 'uses' => 'ManageAdsController@storePlacements']);
    Route::resource('admin/ads', 'ManageAdsController');

    Route::resource('admin', 'DashboardController');
    
    Route::resource('bookmark', 'BookmarkController');
    Route::get('loadTabData', 'BookmarkController@loadTabData');
    Route::post('changeStatus', 'BookmarkController@changeStatus');
    Route::post('deleteChecked', 'BookmarkController@deleteChecked');
    Route::post('saveNotificationOption', 'BookmarkController@saveNotificationOption');
    
    // my profil
    Route::get('/user/{user}/edit', ['as' => 'user.profil.edit', 'uses' => 'MySpaceController@editUserProfil']);
    Route::post('/user/{user}/save', ['as' => 'user.profil.save', 'uses' => 'MySpaceController@saveUserProfil']);
    
});

Route::get('/user/{user}', ['as' => 'user.profil.index', 'uses' => 'MySpaceController@userProfil']);

Route::get('socialCounts', 'FrontController@socialCounts');
Route::get('/', ['as' => 'front.index', 'uses' => 'FrontController@index']);



Route::group(array('before' => 'cache', 'after' => 'cache'), function()
{
    Route::get('/manga/{manga}/{chapter}/{page?}', ['as' => 'front.manga.reader', 'uses' => 'ReaderController@reader'])
        ->where('page', '^[1-9][0-9]*');
});

Route::get('/manga/{manga}', ['as' => 'front.manga.show', 'uses' => 'FrontController@show']);
Route::get('/news/{post}', ['as' => 'front.news', 'uses' => 'FrontController@news']);
Route::get('/latest-release', ['as' => 'front.manga.latestRelease', 'uses' => 'FrontController@latestRelease']);
Route::get('/latest-news', ['as' => 'front.manga.latestNews', 'uses' => 'FrontController@latestNews']);
Route::get('/random', ['as' => 'front.manga.random', 'uses' => 'FrontController@randomManga']);
Route::get('/contact-us', ['as' => 'front.manga.contactUs', 'uses' => 'FrontController@contactUs']);
Route::post('/contact-us', ['as' => 'front.manga.sendMessage', 'uses' => 'FrontController@sendMessage']);
Route::post('/report-bug', ['as' => 'front.manga.reportBug', 'uses' => 'ReaderController@reportBug']);
Route::get('search', 'FrontController@search');

Route::get('filter', 'FrontController@filter');
Route::get('filterList', 'FrontController@filterList');
Route::get('changeMangaList', 'FrontController@changeMangaList');
Route::get('/manga-list/{type?}/{archive?}', ['as' => 'front.manga.list', 'uses' => 'FrontController@mangalist']);
Route::get('/manga-list', ['as' => 'front.manga.list', 'uses' => 'FrontController@mangalist']);

Route::get('/install', ['as' => 'install.index', 'uses' => 'InstallerController@index']);
Route::post('startInstall', 'InstallerController@startInstall');

Route::get('/robots.txt', 'FrontController@robots');
Route::get('/sitemap.xml', 'FrontController@sitemap');
Route::get('/feed', 'FrontController@feed');

Route::when('manga/*', 'manga.view_throttle');

Route::get('/download/{mangaSlug}/{chapterId}', ['as' => 'front.manga.download', 'uses' => 'FrontController@downloadChapter']);

Route::get('/advanced-search', ['as' => 'front.advSearch', 'uses' => 'FrontController@advSearch']);
Route::post('advSearchFilter', 'FrontController@advSearchFilter');

// comment
Route::get('/api/comments/{type}/{id}', ['as' => 'api.comments.index', 'uses' => 'CommentController@index']);
Route::group(array('prefix' => 'api'), function() {
    Route::resource('comments', 'CommentController', array('except' => array('create', 'edit', 'update')));
});

app/views/admin/forgot_password.blade.php
@extends('admin.layouts.auth')

@section('head')
<title>Administration - Forgot Password</title>
@stop

@section('content')
<div class="col-md-6 col-md-offset-3">
    <div class="login-panel panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Forgot Password</h3>
        </div>
        <div class="panel-body">
            <form method="POST" action="{{ URL::to('/users/forgot_password') }}" accept-charset="UTF-8">
                <input type="hidden" name="_token" value="{{{ Session::getToken() }}}">

                <div class="form-group">
                    <label for="email">{{{ Lang::get('confide::confide.e_mail') }}}</label>
                    <div class="input-append input-group">
                        <input class="form-control" placeholder="{{{ Lang::get('confide::confide.e_mail') }}}" type="email" name="email" id="email" value="{{{ Input::old('email') }}}">
                        <span class="input-group-btn">
                            <input class="btn btn-default" type="submit" value="{{{ Lang::get('confide::confide.forgot.submit') }}}">
                        </span>
                    </div>
                </div>
                <br/>
                <div class="form-group">
                    {{HTML::image(Captcha::url())}}
                    {{Form::text('captcha')}}
                </div>
                
                @if (Session::get('error'))
                <div class="alert alert-error alert-danger">{{{ Session::get('error') }}}</div>
                @endif

                @if (Session::get('notice'))
                <div class="alert">{{{ Session::get('notice') }}}</div>
                @endif
            </form>
        </div>
    </div>
</div>
@stop

app/views/admin/index.blade.php
@extends('admin.layouts.default')

@section('breadcrumbs', Breadcrumbs::render('admin.index'))

@section('content')
<div class="row">
    <div class="col-md-12">
        @if (Session::has('updateSuccess'))
        <div class="alert text-center alert-info ">
            {{ Session::get('updateSuccess') }}
        </div>
        @endif
    </div>
    <div class="col-lg-12">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <i class="fa fa-star fa-fw"></i> {{ Lang::get('messages.admin.dashboard.hotmanga') }}
                @if(Entrust::can('manage_hotmanga'))
                <div class="pull-right">
                    {{ link_to_route('admin.manga.hot', Lang::get('messages.admin.dashboard.edit-hotlist'), null, array('class' => 'btn btn-primary btn-xs', 'role' => 'button')) }}
                </div>
                @endif
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                @if (count($hotmanga)>0)
                <ul class="dash_hot">
                    @foreach ($hotmanga as $manga)
                    <li>
                        <a href='{{ url("/admin/manga/{$manga->id}") }}'>
                            @if ($manga->cover)
                            <img width="100" height="100" src='{{asset("uploads/manga/{$manga->slug}/cover/cover_thumb.jpg")}}' alt='{{ $manga->name }}' />
                            @else
                            <img width="100" height="100" src='images/no-image.png' alt='{{ $manga->name }}' />
                            @endif
                            <div class="caption">
                                <h6>{{ $manga->name }}</h6>
                            </div>
                        </a>
                    </li>
                    @endforeach
                </ul>
                @else
                <div class="center-block">
                    <p>{{ Lang::get('messages.admin.dashboard.hotlist-empty') }}</p>
                </div>
                @endif
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-pencil-square-o fa-fw"></i> {{ Lang::get('messages.admin.dashboard.latest-added-manga') }}
                @if(Entrust::can('add_manga'))
                <div class="pull-right">
                    {{ link_to_route('admin.manga.create', Lang::get('messages.admin.dashboard.create-manga'), null, array('class' => 'btn btn-primary btn-xs', 'role' => 'button')) }}
                </div>
                @endif
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                @if (count($mangas)>0)
                <div class="list-group">
                    @foreach ($mangas as $manga)
                    <div class="list-group-item">
                        <div class="media-left">
                            <a href='@if(Entrust::can("view_manga") || Entrust::can("add_manga") || Entrust::can("edit_manga") || Entrust::can("delete_manga")) {{url("/admin/manga/{$manga->id}")}} @endif'>                                
                                @if ($manga->cover)
                                <img width="50" height="50" class="media-object" src='{{asset("uploads/manga/{$manga->slug}/cover/cover_thumb.jpg")}}' alt='{{ $manga->name }}' />
                                @else
                                <img width="50" height="50" src='images/no-image.png' alt='{{ $manga->name }}' />
                                @endif
                            </a>
                        </div>
                        <div class="media-body">
                            <h5 class="media-heading">
                                @if(Entrust::can('view_manga') || Entrust::can('add_manga') || Entrust::can('edit_manga') || Entrust::can('delete_manga'))
                                {{ link_to("/admin/manga/{$manga->id}", $manga->name) }}
                                @else
                                {{ $manga->name }}
                                @endif
                            </h5>
                            <div class="pull-right">
                                <i class="fa fa-user"></i>
                                <small>{{ $manga->user->username }}</small>
                            </div>
                            <div>
                                <i class="fa fa-calendar-o"></i>
                                <small>{{ App::make("HelperController")->formateCreationDate($manga->created_at) }}</small>
                            </div>
                        </div>
                    </div>
                    @endforeach
                </div>
                @if(Entrust::can('view_manga') || Entrust::can('add_manga') || Entrust::can('edit_manga') || Entrust::can('delete_manga'))
                {{ link_to_route('admin.manga.index', Lang::get('messages.admin.dashboard.view-all-manga'), null, array('class' => 'btn btn-default btn-block')) }}
                @endif
                @else
                <div class="center-block">
                    <p>{{ Lang::get('messages.admin.dashboard.no-manga') }}</p>
                </div>
                @endif
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
    <div class="col-lg-6">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-book fa-fw"></i> {{ Lang::get('messages.admin.dashboard.latest-added-chapter') }}
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                @if (count($chapters)>0)
                <div class="list-group">
                    @foreach ($chapters as $chapter)
                    <a href='@if(Entrust::can("view_chapter") || Entrust::can("add_chapter") || Entrust::can("edit_chapter") || Entrust::can("delete_chapter")) {{ url("/admin/manga/{$chapter->manga_id}/chapter/{$chapter->id}") }} @endif' class="list-group-item">
                        <div class="pull-right">
                            <i class="fa fa-user"></i>
                            <small>{{ $chapter->username }}</small>
                        </div>
                        <h5 class="list-group-item-heading">
                            <b>{{ $chapter->manga_name. " #". $chapter->number }}</b>
                        </h5>
                        <div class="pull-right">
                            <i class="fa fa-calendar-o"></i>
                            <small>{{ App::make("HelperController")->formateCreationDate($chapter->created_at) }}</small>
                        </div>
                        <p class="list-group-item-text"><em>{{ $chapter->name }}</em></p>

                    </a>
                    @endforeach
                </div>
                @else
                <div class="center-block">
                    <p>{{ Lang::get('messages.admin.dashboard.no-chapter') }}</p>
                </div>
                @endif
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>
@stop

app/views/admin/login.blade.php
@extends('admin.layouts.auth')

@section('head')
<title>Administration - Login Page</title>
@stop

@section('content')
<div class="col-md-4 col-md-offset-4">
    <div class="login-panel panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Please Sign In</h3>
        </div>
        <div class="panel-body">
            <form role="form" method="POST" action="{{{ URL::to('/users/login') }}}" accept-charset="UTF-8">
                <input type="hidden" name="_token" value="{{{ Session::getToken() }}}">
                <fieldset>
                    <div class="form-group">
                        <input class="form-control" tabindex="1" placeholder="{{{ Lang::get('confide::confide.username_e_mail') }}}" type="text" name="email" id="email" value="{{{ Input::old('email') }}}">
                    </div>
                    <div class="form-group">
                        <input class="form-control" tabindex="2" placeholder="{{{ Lang::get('confide::confide.password') }}}" type="password" name="password" id="password">
                        <p class="help-block">
                            <a href="{{{ URL::to('/users/forgot_password') }}}">{{{ Lang::get('confide::confide.login.forgot_password') }}}</a>
                        </p>
                    </div>
                    <div class="checkbox">
                        <label for="remember">
                            <input tabindex="4" type="checkbox" name="remember" id="remember" value="1"> {{{ Lang::get('confide::confide.login.remember') }}}
                        </label>
                    </div>
                    <br/>
                    <div class="form-group">
                    {{HTML::image(Captcha::url())}}
                    {{Form::text('captcha')}}
                    </div>
        
                    @if (Session::get('error'))
                    <div class="alert alert-error alert-danger">{{{ Session::get('error') }}}</div>
                    @endif

                    @if (Session::get('notice'))
                    <div class="alert">{{{ Session::get('notice') }}}</div>
                    @endif
                    <div class="form-group">
                        <button tabindex="3" type="submit" class="btn btn-lg btn-success btn-block">{{{ Lang::get('confide::confide.login.submit') }}}</button>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>
@stop

app/views/admin/reset_password.blade.php
@extends('admin.layouts.auth')

@section('head')
<title>Administration - Reset Password</title>
@stop

@section('content')
<div class="col-md-6 col-md-offset-3">
    <div class="login-panel panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Reset Password</h3>
        </div>
        <div class="panel-body">
            <form method="POST" action="{{{ URL::to('/users/reset_password') }}}" accept-charset="UTF-8">
                <input type="hidden" name="token" value="{{{ $token }}}">
                <input type="hidden" name="_token" value="{{{ Session::getToken() }}}">

                <div class="form-group">
                    <label for="password">{{{ Lang::get('confide::confide.password') }}}</label>
                    <input class="form-control" placeholder="{{{ Lang::get('confide::confide.password') }}}" type="password" name="password" id="password">
                </div>
                <div class="form-group">
                    <label for="password_confirmation">{{{ Lang::get('confide::confide.password_confirmation') }}}</label>
                    <input class="form-control" placeholder="{{{ Lang::get('confide::confide.password_confirmation') }}}" type="password" name="password_confirmation" id="password_confirmation">
                </div>

                @if (Session::get('error'))
                <div class="alert alert-error alert-danger">{{{ Session::get('error') }}}</div>
                @endif

                @if (Session::get('notice'))
                <div class="alert">{{{ Session::get('notice') }}}</div>
                @endif

                <div class="form-actions form-group">
                    <button type="submit" class="btn btn-primary">{{{ Lang::get('confide::confide.forgot.submit') }}}</button>
                </div>
            </form>
        </div>
    </div>
</div>
@stop

app/views/admin/signup.blade.php
@extends('admin.layouts.auth')

@section('head')
<title>Administration - Sign Up</title>
@stop

@section('content')
<div class="col-md-6 col-md-offset-3">
    <div class="login-panel panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Sign Up</h3>
        </div>
        <div class="panel-body">
            <form method="POST" action="{{{ URL::to('users') }}}" accept-charset="UTF-8">
                <input type="hidden" name="_token" value="{{{ Session::getToken() }}}">
                <fieldset>
                    @if (Cache::remember('username_in_confide', 5, function() {
                    return Schema::hasColumn(Config::get('auth.table'), 'username');
                    }))
                    <div class="form-group">
                        <label for="username">{{{ Lang::get('confide::confide.username') }}}</label>
                        <input class="form-control" placeholder="{{{ Lang::get('confide::confide.username') }}}" type="text" name="username" id="username" value="{{{ Input::old('username') }}}">
                    </div>
                    @endif
                    <div class="form-group">
                        <label for="email">{{{ Lang::get('confide::confide.e_mail') }}} @if(Config::get('confide::signup_email'))<small>{{ Lang::get('confide::confide.signup.confirmation_required') }}</small>@endif</label>
                        <input class="form-control" placeholder="{{{ Lang::get('confide::confide.e_mail') }}}" type="text" name="email" id="email" value="{{{ Input::old('email') }}}">
                    </div>
                    <div class="form-group">
                        <label for="password">{{{ Lang::get('confide::confide.password') }}}</label>
                        <input class="form-control" placeholder="{{{ Lang::get('confide::confide.password') }}}" type="password" name="password" id="password">
                    </div>
                    <div class="form-group">
                        <label for="password_confirmation">{{{ Lang::get('confide::confide.password_confirmation') }}}</label>
                        <input class="form-control" placeholder="{{{ Lang::get('confide::confide.password_confirmation') }}}" type="password" name="password_confirmation" id="password_confirmation">
                    </div>

                    <br/>
                    <div class="form-group">
                        {{HTML::image(Captcha::url())}}
                        {{Form::text('captcha')}}
                    </div>

                    @if (Session::get('error'))
                    <div class="alert alert-error alert-danger">
                        @if (is_array(Session::get('error')))
                        {{ head(Session::get('error')) }}
                        @endif
                    </div>
                    @endif

                    @if (Session::get('notice'))
                    <div class="alert">{{ Session::get('notice') }}</div>
                    @endif

                    <div class="form-actions form-group">
                        <button type="submit" class="btn btn-primary">{{{ Lang::get('confide::confide.signup.submit') }}}</button>
                    </div>

                </fieldset>
            </form>
        </div>
    </div>
</div>
@stop