app/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the Closure to execute when that URI is requested.
  |
 */

// Confide routes
Route::get('users/create', 'UsersController@create');
Route::post('users', 'UsersController@store');
Route::get('admin/login', 'UsersController@login');
Route::post('users/login', 'UsersController@doLogin');
Route::get('users/confirm/{code}', 'UsersController@confirm');
Route::get('users/forgot_password', 'UsersController@forgotPassword');
Route::post('users/forgot_password', 'UsersController@doForgotPassword');
Route::get('users/reset_password/{token}', 'UsersController@resetPassword');
Route::post('users/reset_password', 'UsersController@doResetPassword');
Route::get('admin/logout', ['as' => 'admin.logout', 'uses' => 'UsersController@logout']);

Route::group(['before' => 'auth'], function () {
    Route::get('admin/hot-manga', ['as' => 'admin.manga.hot', 'uses' => 'MangaController@hotManga']);
    Route::post('autoMangaInfo', ['as' => 'admin.manga.autoMangaInfo', 'uses' => 'MangaController@autoMangaInfo']);
    Route::post('updateHotManga', 'MangaController@updateHotManga');
	
    Route::get('admin/options-manga', ['as' => 'admin.manga.options', 'uses' => 'MangaController@mangaOptions']);
    Route::post('saveMangaOptions', ['as' => 'admin.manga.options.save', 'uses' => 'MangaController@saveMangaOptions']);
    Route::get('admin/filterMangaList', 'MangaController@filterList');
    Route::resource('admin/manga', 'MangaController');
    
    Route::get('admin/manga/{manga}/chapter/scraper', ['as' => 'admin.manga.chapter.scraper', 'uses' => 'WebScraperController@scraper']);
    Route::post('startScraper', 'WebScraperController@startScraper');
    Route::post('getTotalChapters', 'WebScraperController@getTotalChapters');
    Route::post('getChapter', 'WebScraperController@getChapter');
    Route::post('abort', 'WebScraperController@abort');
    Route::post('resume', 'WebScraperController@resume');

    
    Route::delete('admin/destroyChapters/{mangaId}', ['as' => 'admin.manga.chapter.destroyChapters', 'uses' => 'ChapterController@destroyChapters']);
    Route::post('notifyUsers', 'ChapterController@notifyUsers');
    Route::resource('admin/manga.chapter', 'ChapterController');

    Route::delete('admin/destroyPages/{mangaId}/{chapterId}', ['as' => 'admin.manga.chapter.page.destroyPages', 'uses' => 'PageController@destroyPages']);
    Route::post('downloadImageFromUrl', 'PageController@downloadImageFromUrl');
    Route::post('uploadZIPFile', 'PageController@uploadZIPFile');
    Route::post('createExternalPages', 'PageController@createExternalPages');
    Route::post('movePage', 'PageController@movePage');
    Route::resource('admin/manga.chapter.page', 'PageController');

    Route::resource('admin/category', 'CategoryController');

    // CKeditor upload image
    Route::post('admin/uploadPostImage', ['as' => 'admin.posts.uploadImage', 'uses' => 'PostController@uploadImage']);
    Route::get('admin/uploadBrowseImage', ['as' => 'admin.posts.browseImage', 'uses' => 'PostController@browseImage']);
    Route::post('admin/deletePostImage', ['as' => 'admin.posts.deletePostImage', 'uses' => 'PostController@deletePostImage']);

    Route::resource('admin/comictype', 'ComicTypeController');
    Route::resource('admin/posts', 'PostController');

    // Settings
    Route::get('admin/general', ['as' => 'admin.settings.general', 'uses' => 'SettingsController@general']);
    Route::post('admin/general', ['as' => 'admin.settings.general.save', 'uses' => 'SettingsController@saveGeneral']);

    Route::get('admin/seo', ['as' => 'admin.settings.seo', 'uses' => 'SettingsController@seo']);
    Route::post('admin/seo', ['as' => 'admin.settings.seo.save', 'uses' => 'SettingsController@saveSeo']);

    Route::get('admin/profile', ['as' => 'admin.settings.profile', 'uses' => 'SettingsController@profile']);
    Route::post('admin/profile', ['as' => 'admin.settings.profile.save', 'uses' => 'SettingsController@saveProfile']);

    Route::get('admin/theme', ['as' => 'admin.settings.theme', 'uses' => 'SettingsController@theme']);
    Route::post('admin/theme', ['as' => 'admin.settings.theme.save', 'uses' => 'SettingsController@saveTheme']);

    Route::get('admin/widgets', ['as' => 'admin.settings.widgets', 'uses' => 'SettingsController@widgets']);
    Route::post('admin/widgets', ['as' => 'admin.settings.widgets.save', 'uses' => 'SettingsController@saveWidgets']);

    Route::get('admin/cache', ['as' => 'admin.settings.cache', 'uses' => 'SettingsController@cache']);
    Route::post('admin/cache', ['as' => 'admin.settings.cache.save', 'uses' => 'SettingsController@saveCache']);
    Route::post('admin/clear-cache', ['as' => 'admin.settings.cache.clear', 'uses' => 'SettingsController@clearCache']);
    Route::post('admin/clear-downloads', ['as' => 'admin.settings.downloads.clear', 'uses' => 'SettingsController@clearDownloads']);

    // Google
    Route::get('admin/gdrive', ['as' => 'admin.settings.gdrive', 'uses' => 'Cyberziko\Gdrive\Controllers\GoogleController@index']);
    Route::post('admin/gdrive/reset', ['as' => 'admin.settings.gdrive.reset', 'uses' => 'Cyberziko\Gdrive\Controllers\GoogleController@resetGdrive']);
    Route::post('admin/gdrive', ['as' => 'admin.settings.gdrive.save', 'uses' => 'Cyberziko\Gdrive\Controllers\GoogleController@saveGdrive']);

    Route::post('saveSubscription', ['as' => 'admin.users.subsciption', 'uses' => 'ManageUserController@saveSubscription']);
    Route::get('admin/permissions', ['as' => 'admin.users.permissions', 'uses' => 'ManageUserController@permissions']);
    Route::resource('admin/role', 'RoleController');
    Route::resource('admin/user', 'ManageUserController');

    Route::post('uploadMangaCover', 'FileUploadController@uploadMangaCover');
    Route::post('uploadMangaChapterPage', 'FileUploadController@uploadMangaChapterPage');
    Route::post('deleteImage', 'FileUploadController@deleteImage');
    Route::post('deleteCover', 'FileUploadController@deleteCover');
    Route::post('uploadAvatar', 'FileUploadController@uploadAvatar');
    Route::post('deleteAvatar', 'FileUploadController@deleteAvatar');

    Route::post('admin/ads/storePlacements', ['as' => 'admin.ads.storePlacements', 'uses' => 'ManageAdsController@storePlacements']);
    Route::resource('admin/ads', 'ManageAdsController');

    Route::resource('admin', 'DashboardController');
    
    Route::resource('bookmark', 'BookmarkController');
    Route::get('loadTabData', 'BookmarkController@loadTabData');
    Route::post('changeStatus', 'BookmarkController@changeStatus');
    Route::post('deleteChecked', 'BookmarkController@deleteChecked');
    Route::post('saveNotificationOption', 'BookmarkController@saveNotificationOption');
    
    // my profil
    Route::get('/user/{user}/edit', ['as' => 'user.profil.edit', 'uses' => 'MySpaceController@editUserProfil']);
    Route::post('/user/{user}/save', ['as' => 'user.profil.save', 'uses' => 'MySpaceController@saveUserProfil']);
    
});

Route::get('/user/{user}', ['as' => 'user.profil.index', 'uses' => 'MySpaceController@userProfil']);

Route::get('socialCounts', 'FrontController@socialCounts');
Route::get('/', ['as' => 'front.index', 'uses' => 'FrontController@index']);



Route::group(array('before' => 'cache', 'after' => 'cache'), function()
{
    Route::get('/manga/{manga}/{chapter}/{page?}', ['as' => 'front.manga.reader', 'uses' => 'ReaderController@reader'])
        ->where('page', '^[1-9][0-9]*');
});

Route::get('/manga/{manga}', ['as' => 'front.manga.show', 'uses' => 'FrontController@show']);
Route::get('/news/{post}', ['as' => 'front.news', 'uses' => 'FrontController@news']);
Route::get('/latest-release', ['as' => 'front.manga.latestRelease', 'uses' => 'FrontController@latestRelease']);
Route::get('/latest-news', ['as' => 'front.manga.latestNews', 'uses' => 'FrontController@latestNews']);
Route::get('/random', ['as' => 'front.manga.random', 'uses' => 'FrontController@randomManga']);
Route::get('/contact-us', ['as' => 'front.manga.contactUs', 'uses' => 'FrontController@contactUs']);
Route::post('/contact-us', ['as' => 'front.manga.sendMessage', 'uses' => 'FrontController@sendMessage']);
Route::post('/report-bug', ['as' => 'front.manga.reportBug', 'uses' => 'ReaderController@reportBug']);
Route::get('search', 'FrontController@search');

Route::get('filter', 'FrontController@filter');
Route::get('filterList', 'FrontController@filterList');
Route::get('changeMangaList', 'FrontController@changeMangaList');
Route::get('/manga-list/{type?}/{archive?}', ['as' => 'front.manga.list', 'uses' => 'FrontController@mangalist']);
Route::get('/manga-list', ['as' => 'front.manga.list', 'uses' => 'FrontController@mangalist']);

Route::get('/install', ['as' => 'install.index', 'uses' => 'InstallerController@index']);
Route::post('startInstall', 'InstallerController@startInstall');

Route::get('/robots.txt', 'FrontController@robots');
Route::get('/sitemap.xml', 'FrontController@sitemap');
Route::get('/feed', 'FrontController@feed');

Route::when('manga/*', 'manga.view_throttle');

Route::get('/download/{mangaSlug}/{chapterId}', ['as' => 'front.manga.download', 'uses' => 'FrontController@downloadChapter']);

Route::get('/advanced-search', ['as' => 'front.advSearch', 'uses' => 'FrontController@advSearch']);
Route::post('advSearchFilter', 'FrontController@advSearchFilter');

// comment
Route::get('/api/comments/{type}/{id}', ['as' => 'api.comments.index', 'uses' => 'CommentController@index']);
Route::group(array('prefix' => 'api'), function() {
    Route::resource('comments', 'CommentController', array('except' => array('create', 'edit', 'update')));
});

app/controllers/UsersController.php
<?php



/**
 * UsersController Class
 *
 * Implements actions regarding user management
 */
class UsersController extends Controller
{

    /**
     * Displays the form for account creation
     *
     * @return  Illuminate\Http\Response
     */
    public function create()
    {
        if (!Config::get('subscribe')) {
            return Redirect::to('/');
        } else {
            return View::make('admin.signup');
        }
    }

    /**
     * Stores new account
     *
     * @return  Illuminate\Http\Response
     */
    public function store()
    {
        if (HelperController::isValidCaptcha(Input::all())) {
            $repo = App::make('UserRepository');
            $user = $repo->signup(Input::all());

            if ($user->id) {
                // assign default role
                $roles[0]=Config::get('default_role');
                $user->roles()->sync($roles);

                if (Config::get('confide::signup_email')) {
                    Mail::queueOn(
                        Config::get('confide::email_queue'),
                        Config::get('confide::email_account_confirmation'),
                        compact('user'),
                        function ($message) use ($user) {
                            $message
                                ->to($user->email, $user->username)
                                ->subject(Lang::get('confide::confide.email.account_confirmation.subject'));
                        }
                    );
                }

                return Redirect::action('UsersController@login')
                    ->with('notice', Lang::get('confide::confide.alerts.account_created'));
            } else {
                $error = $user->errors()->all(':message');

                return Redirect::action('UsersController@create')
                    ->withInput(Input::except('password'))
                    ->with('error', $error);
            }
        } else {
            return Redirect::action('UsersController@create')
                    ->withInput(Input::except('password'))
                    ->with('error', array("Invalid Captcha!"));
        }
    }

    /**
     * Displays the login form
     *
     * @return  Illuminate\Http\Response
     */
    public function login()
    {
        if (Confide::user()) {
            return Redirect::to('admin');
        } else {
            return View::make('admin.login');
        }
    }

    /**
     * Attempt to do login
     *
     * @return  Illuminate\Http\Response
     */
    public function doLogin()
    {
        $repo = App::make('UserRepository');
        $input = Input::all();
        
        if (HelperController::isValidCaptcha($input)) {
            if ($repo->login($input)) {
                return Redirect::to('/');
            } else {
                if ($repo->isThrottled($input)) {
                    $err_msg = Lang::get('confide::confide.alerts.too_many_attempts');
                } elseif ($repo->existsButNotConfirmed($input)) {
                    $err_msg = Lang::get('confide::confide.signup.confirmation_required');
                    // $err_msg = Lang::get('confide::confide.alerts.not_confirmed');
                } else {
                    $err_msg = Lang::get('confide::confide.alerts.wrong_credentials');
                }

                return Redirect::action('UsersController@login')
                                ->withInput(Input::except('password'))
                                ->with('error', $err_msg);
            }
        } else {
            return Redirect::action('UsersController@login')
                            ->withInput(Input::except('password'))
                            ->with('error', "Invalid Captcha!");
        }
    }

    /**
     * Attempt to confirm account with code
     *
     * @param  string $code
     *
     * @return  Illuminate\Http\Response
     */
    public function confirm($code)
    {
        if (Confide::confirm($code)) {
            $notice_msg = Lang::get('confide::confide.alerts.confirmation');
            return Redirect::action('UsersController@login')
                ->with('notice', $notice_msg);
        } else {
            $error_msg = Lang::get('confide::confide.alerts.wrong_confirmation');
            return Redirect::action('UsersController@login')
                ->with('error', $error_msg);
        }
    }

    /**
     * Displays the forgot password form
     *
     * @return  Illuminate\Http\Response
     */
    public function forgotPassword()
    {
        return View::make('admin.forgot_password');
    }

    /**
     * Attempt to send change password link to the given email
     *
     * @return  Illuminate\Http\Response
     */
    public function doForgotPassword()
    {
        if (HelperController::isValidCaptcha(Input::all())) {
            if (Confide::forgotPassword(Input::get('email'))) {
                $notice_msg = Lang::get('confide::confide.alerts.password_forgot');
                return Redirect::action('UsersController@login')
                    ->with('notice', $notice_msg);
            } else {
                $error_msg = Lang::get('confide::confide.alerts.wrong_password_forgot');
                return Redirect::action('UsersController@doForgotPassword')
                    ->withInput()
                    ->with('error', $error_msg);
            }
        } else {
            return Redirect::action('UsersController@doForgotPassword')
                    ->withInput()
                    ->with('error', "Invalid Captcha!");
        }
    }

    /**
     * Shows the change password form with the given token
     *
     * @param  string $token
     *
     * @return  Illuminate\Http\Response
     */
    public function resetPassword($token)
    {
        return View::make('admin.reset_password')
                ->with('token', $token);
    }

    /**
     * Attempt change password of the user
     *
     * @return  Illuminate\Http\Response
     */
    public function doResetPassword()
    {
        $repo = App::make('UserRepository');
        $input = array(
            'token'                 =>Input::get('token'),
            'password'              =>Input::get('password'),
            'password_confirmation' =>Input::get('password_confirmation'),
        );

        // By passing an array with the token, password and confirmation
        if ($repo->resetPassword($input)) {
            $notice_msg = Lang::get('confide::confide.alerts.password_reset');
            return Redirect::action('UsersController@login')
                ->with('notice', $notice_msg);
        } else {
            $error_msg = Lang::get('confide::confide.alerts.wrong_password_reset');
            return Redirect::action('UsersController@resetPassword', array('token'=>$input['token']))
                ->withInput()
                ->with('error', $error_msg);
        }
    }

    /**
     * Log the user out of the application.
     *
     * @return  Illuminate\Http\Response
     */
    public function logout()
    {
        Confide::logout();

        return Redirect::to('/');
    }
}

app/views/admin/users/user/index.blade.php
@extends('admin.layouts.default')

@section('head')
{{ HTML::style('css/bootstrap-select.min.css') }}

{{ HTML::script('js/vendor/bootstrap-select.min.js') }}
@stop

@section('breadcrumbs', Breadcrumbs::render())

@section('content')
<div>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active">
            <a href="#users" aria-controls="users" role="tab" data-toggle="tab">{{ Lang::get('messages.admin.users.users') }}</a>
        </li>
        <li role="presentation">
            <a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">{{ Lang::get('messages.admin.users.options') }}</a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="users">
            <div class="row">
                <div class="col-xs-12">
                    @if (Session::has('createSuccess'))
                    <div class="alert text-center alert-info ">
                        {{ Session::get('createSuccess') }}
                    </div>
                    @endif

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-users fa-fw"></i> {{ Lang::get('messages.admin.users.users') }}
                            <div class="pull-right">
                                {{ link_to_route('admin.user.create', Lang::get('messages.admin.users.add'), null, array('class' => 'btn btn-primary btn-xs pull-right', 'role' => 'button')) }}
                            </div>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="table-responsive">
                                        <table class="table table-hover">
                                            <thead>
                                                <tr>
                                                    <th>{{ Lang::get('messages.admin.users.username') }}</th>
                                                    <th>{{ Lang::get('messages.admin.users.email') }}</th>
                                                    <th>{{ Lang::get('messages.admin.users.roles') }}</th>
                                                    <th>{{ Lang::get('messages.admin.users.status') }}</th>
                                                    <th>{{ Lang::get('messages.admin.users.manga') }}</th>
                                                    <th>{{ Lang::get('messages.admin.users.chapters') }}</th>
                                                    <th></th>
                                                </tr>
                                            </thead>
                                            @if(count($users)>0)
                                            @foreach($users as $user)
                                            <tr>
                                                <td>{{ $user->username }}</td>
                                                <td>{{ $user->email }}</td>
                                                <td>{{ App::make("HelperController")->listAsString($user->roles, ', ') }}</td>
                                                <td>@if($user->confirmed == 1) <span class="label label-success">{{ Lang::get('messages.admin.users.enabled') }}</span> @else <span class="label label-danger">{{ Lang::get('messages.admin.users.disabled') }}</span> @endif </td>
                                                <td>{{ count($user->manga) }}</td>
                                                <td>{{ count($user->chapters) }}</td>
                                                <td style="text-align: right;"> @if($user->id != 1)
                                                    {{ link_to_route('admin.user.edit', Lang::get('messages.admin.users.edit'), $user->id, array('class' => 'btn btn-primary btn-xs')); }}
                                                    <div style="display: inline-block">
                                                        {{ Form::open(array('route' => array('admin.user.destroy', $user->id), 'method' => 'delete')) }}
                                                        {{ Form::submit(Lang::get('messages.admin.users.delete'), array('class' => 'btn btn-danger btn-xs',  'onclick' => 'if (!confirm("'.Lang::get('messages.admin.users.confirm-delete').'")) {return false;}')) }}
                                                        {{ Form::close() }}
                                                    </div> @endif</td>
                                            </tr>
                                            @endforeach
                                            @endif
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                </div>
            </div>
        </div>
        <div role="tabpanel" class="tab-pane" id="settings">
            <div class="row">
                <div class="col-xs-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-12">
                                    {{ Form::open(array('route' => 'admin.users.subsciption')) }}
                                    <div class="form-group">
                                        <label style="vertical-align: text-top;">{{ Lang::get('messages.admin.users.options.allo-subscribe') }}</label>
                                        <label class="radio-inline">
                                            <input type="radio" name="subscribe" value="true" <?php if ($subscription->subscribe === 'true'): ?>
                                                   checked="checked"<?php endif ?>/>{{ Lang::get('messages.admin.users.options.yes') }}</label>
                                        <label class="radio-inline">
                                            <input type="radio" name="subscribe" value="false" <?php if ($subscription->subscribe === 'false'): ?>
                                                   checked="checked"<?php endif ?>/>{{ Lang::get('messages.admin.users.options.no') }}</label>
                                    </div>
                                    <hr/>
                                    <p>
                                        {{ Lang::get('messages.admin.users.options.new-account') }}
                                    </p>
                                    <div class="form-group">
                                        <label style="vertical-align: text-top;">{{ Lang::get('messages.admin.users.options.admin-activate-it') }}</label>
                                        <label class="radio-inline">
                                            <input type="radio" name="admin_confirm" value="true" <?php if ($subscription->admin_confirm === 'true'): ?>
                                                   checked="checked"<?php endif ?>/>{{ Lang::get('messages.admin.users.options.yes') }}</label>
                                        <label class="radio-inline">
                                            <input type="radio" name="admin_confirm" value="false" <?php if ($subscription->admin_confirm === 'false'): ?>
                                                   checked="checked"<?php endif ?>/>{{ Lang::get('messages.admin.users.options.no') }}</label>
                                    </div>
                                    <div class="form-group">
                                        <label style="vertical-align: text-top;">{{ Lang::get('messages.admin.users.options.send-confim-email') }}</label>
                                        <label class="radio-inline">
                                            <input type="radio" name="email_confirm" value="true" <?php if ($subscription->email_confirm === 'true'): ?>
                                                   checked="checked"<?php endif ?>/>{{ Lang::get('messages.admin.users.options.yes') }}</label>
                                        <label class="radio-inline">
                                            <input type="radio" name="email_confirm" value="false" <?php if ($subscription->email_confirm === 'false'): ?>
                                                   checked="checked"<?php endif ?>/>{{ Lang::get('messages.admin.users.options.no') }}</label>
                                    </div>
                                    <div class="form-group">
                                        {{Form::label('default_role', Lang::get('messages.admin.users.options.default-role'))}}
                                        {{Form::select('default_role', $roles, $subscription->default_role, array('class' => 'selectpicker', 'data-width' => '100%'))}}
                                    </div>
                                    <hr/>
                                    <p>
                                        {{ Lang::get('messages.admin.users.options.mail-conf') }}
                                    </p>
                                    <div id="mailing" class="form-group">
                                        <div class="form-group">
                                            <label>{{ Lang::get('messages.admin.users.options.address') }}</label>
                                            <input type="text" name="address" value="{{ $subscription->address }}" class="form-control"/>
                                        </div>
                                        <div class="form-group">
                                            <label>{{ Lang::get('messages.admin.users.options.name') }}</label>
                                            <input type="text" name="name" value="{{ $subscription->name }}" class="form-control"/>
                                        </div>
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="mailing" value="sendmail" <?php if ($subscription->mailing === 'sendmail'): ?>
                                                       checked="checked"<?php endif ?>/>{{ Lang::get('messages.admin.users.options.use-php-mail') }}</label>
                                        </div>
                                        <div class="radio">
                                            <label>
                                                <input type="radio" name="mailing" value="smtp" <?php if ($subscription->mailing === 'smtp'): ?>
                                                       checked="checked"<?php endif ?>/>{{ Lang::get('messages.admin.users.options.config-smtp') }}</label>
                                        </div>

                                        <div id="smtp-conf" style="display: none;">
                                            <div class="form-group">
                                                <label>{{ Lang::get('messages.admin.users.options.host') }}</label>
                                                <input type="text" name="host" value="{{ $subscription->host }}" class="form-control"/>
                                            </div>
                                            <div class="form-group">
                                                <label>{{ Lang::get('messages.admin.users.options.port') }}</label>
                                                <input type="text" name="port" value="{{ $subscription->port }}" class="form-control"/>
                                            </div>
                                            <div class="form-group">
                                                <label>{{ Lang::get('messages.admin.users.options.username') }}</label>
                                                <input type="text" name="username" value="{{ $subscription->username }}" class="form-control"/>
                                            </div>
                                            <div class="form-group">
                                                <label>{{ Lang::get('messages.admin.users.options.password') }}</label>
                                                <input type="password" name="password" value="{{ $subscription->password }}" class="form-control"/>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div>
                                {{ Form::submit(Lang::get('messages.admin.settings.update'), array('class' => 'btn btn-primary center-block save', 'style' => 'width: 100%')) }}
                            </div>
                            {{ Form::close() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        smtpChecked();
    });

    $('#mailing input[type="radio"]').change(function () {
        smtpChecked();
    });

    function smtpChecked() {
        if ($('#mailing input[value="smtp"]').is(':checked')) {
            $('#smtp-conf').show();
        } else {
            $('#smtp-conf').hide();
        }
    }
</script>
@stop