app/routes.php
<?php

/*
  |--------------------------------------------------------------------------
  | Application Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register all of the routes for an application.
  | It's a breeze. Simply tell Laravel the URIs it should respond to
  | and give it the Closure to execute when that URI is requested.
  |
 */

// Confide routes
Route::get('users/create', 'UsersController@create');
Route::post('users', 'UsersController@store');
Route::get('admin/login', 'UsersController@login');
Route::post('users/login', 'UsersController@doLogin');
Route::get('users/confirm/{code}', 'UsersController@confirm');
Route::get('users/forgot_password', 'UsersController@forgotPassword');
Route::post('users/forgot_password', 'UsersController@doForgotPassword');
Route::get('users/reset_password/{token}', 'UsersController@resetPassword');
Route::post('users/reset_password', 'UsersController@doResetPassword');
Route::get('admin/logout', ['as' => 'admin.logout', 'uses' => 'UsersController@logout']);

Route::group(['before' => 'auth'], function () {
    Route::get('admin/hot-manga', ['as' => 'admin.manga.hot', 'uses' => 'MangaController@hotManga']);
    Route::post('autoMangaInfo', ['as' => 'admin.manga.autoMangaInfo', 'uses' => 'MangaController@autoMangaInfo']);
    Route::post('updateHotManga', 'MangaController@updateHotManga');
	
    Route::get('admin/options-manga', ['as' => 'admin.manga.options', 'uses' => 'MangaController@mangaOptions']);
    Route::post('saveMangaOptions', ['as' => 'admin.manga.options.save', 'uses' => 'MangaController@saveMangaOptions']);
    Route::get('admin/filterMangaList', 'MangaController@filterList');
    Route::resource('admin/manga', 'MangaController');
    
    Route::get('admin/manga/{manga}/chapter/scraper', ['as' => 'admin.manga.chapter.scraper', 'uses' => 'WebScraperController@scraper']);
    Route::post('startScraper', 'WebScraperController@startScraper');
    Route::post('getTotalChapters', 'WebScraperController@getTotalChapters');
    Route::post('getChapter', 'WebScraperController@getChapter');
    Route::post('abort', 'WebScraperController@abort');
    Route::post('resume', 'WebScraperController@resume');

    
    Route::delete('admin/destroyChapters/{mangaId}', ['as' => 'admin.manga.chapter.destroyChapters', 'uses' => 'ChapterController@destroyChapters']);
    Route::post('notifyUsers', 'ChapterController@notifyUsers');
    Route::resource('admin/manga.chapter', 'ChapterController');

    Route::delete('admin/destroyPages/{mangaId}/{chapterId}', ['as' => 'admin.manga.chapter.page.destroyPages', 'uses' => 'PageController@destroyPages']);
    Route::post('downloadImageFromUrl', 'PageController@downloadImageFromUrl');
    Route::post('uploadZIPFile', 'PageController@uploadZIPFile');
    Route::post('createExternalPages', 'PageController@createExternalPages');
    Route::post('movePage', 'PageController@movePage');
    Route::resource('admin/manga.chapter.page', 'PageController');

    Route::resource('admin/category', 'CategoryController');

    // CKeditor upload image
    Route::post('admin/uploadPostImage', ['as' => 'admin.posts.uploadImage', 'uses' => 'PostController@uploadImage']);
    Route::get('admin/uploadBrowseImage', ['as' => 'admin.posts.browseImage', 'uses' => 'PostController@browseImage']);
    Route::post('admin/deletePostImage', ['as' => 'admin.posts.deletePostImage', 'uses' => 'PostController@deletePostImage']);

    Route::resource('admin/comictype', 'ComicTypeController');
    Route::resource('admin/posts', 'PostController');

    // Settings
    Route::get('admin/general', ['as' => 'admin.settings.general', 'uses' => 'SettingsController@general']);
    Route::post('admin/general', ['as' => 'admin.settings.general.save', 'uses' => 'SettingsController@saveGeneral']);

    Route::get('admin/seo', ['as' => 'admin.settings.seo', 'uses' => 'SettingsController@seo']);
    Route::post('admin/seo', ['as' => 'admin.settings.seo.save', 'uses' => 'SettingsController@saveSeo']);

    Route::get('admin/profile', ['as' => 'admin.settings.profile', 'uses' => 'SettingsController@profile']);
    Route::post('admin/profile', ['as' => 'admin.settings.profile.save', 'uses' => 'SettingsController@saveProfile']);

    Route::get('admin/theme', ['as' => 'admin.settings.theme', 'uses' => 'SettingsController@theme']);
    Route::post('admin/theme', ['as' => 'admin.settings.theme.save', 'uses' => 'SettingsController@saveTheme']);

    Route::get('admin/widgets', ['as' => 'admin.settings.widgets', 'uses' => 'SettingsController@widgets']);
    Route::post('admin/widgets', ['as' => 'admin.settings.widgets.save', 'uses' => 'SettingsController@saveWidgets']);

    Route::get('admin/cache', ['as' => 'admin.settings.cache', 'uses' => 'SettingsController@cache']);
    Route::post('admin/cache', ['as' => 'admin.settings.cache.save', 'uses' => 'SettingsController@saveCache']);
    Route::post('admin/clear-cache', ['as' => 'admin.settings.cache.clear', 'uses' => 'SettingsController@clearCache']);
    Route::post('admin/clear-downloads', ['as' => 'admin.settings.downloads.clear', 'uses' => 'SettingsController@clearDownloads']);

    // Google
    Route::get('admin/gdrive', ['as' => 'admin.settings.gdrive', 'uses' => 'Cyberziko\Gdrive\Controllers\GoogleController@index']);
    Route::post('admin/gdrive/reset', ['as' => 'admin.settings.gdrive.reset', 'uses' => 'Cyberziko\Gdrive\Controllers\GoogleController@resetGdrive']);
    Route::post('admin/gdrive', ['as' => 'admin.settings.gdrive.save', 'uses' => 'Cyberziko\Gdrive\Controllers\GoogleController@saveGdrive']);

    Route::post('saveSubscription', ['as' => 'admin.users.subsciption', 'uses' => 'ManageUserController@saveSubscription']);
    Route::get('admin/permissions', ['as' => 'admin.users.permissions', 'uses' => 'ManageUserController@permissions']);
    Route::resource('admin/role', 'RoleController');
    Route::resource('admin/user', 'ManageUserController');

    Route::post('uploadMangaCover', 'FileUploadController@uploadMangaCover');
    Route::post('uploadMangaChapterPage', 'FileUploadController@uploadMangaChapterPage');
    Route::post('deleteImage', 'FileUploadController@deleteImage');
    Route::post('deleteCover', 'FileUploadController@deleteCover');
    Route::post('uploadAvatar', 'FileUploadController@uploadAvatar');
    Route::post('deleteAvatar', 'FileUploadController@deleteAvatar');

    Route::post('admin/ads/storePlacements', ['as' => 'admin.ads.storePlacements', 'uses' => 'ManageAdsController@storePlacements']);
    Route::resource('admin/ads', 'ManageAdsController');

    Route::resource('admin', 'DashboardController');
    
    Route::resource('bookmark', 'BookmarkController');
    Route::get('loadTabData', 'BookmarkController@loadTabData');
    Route::post('changeStatus', 'BookmarkController@changeStatus');
    Route::post('deleteChecked', 'BookmarkController@deleteChecked');
    Route::post('saveNotificationOption', 'BookmarkController@saveNotificationOption');
    
    // my profil
    Route::get('/user/{user}/edit', ['as' => 'user.profil.edit', 'uses' => 'MySpaceController@editUserProfil']);
    Route::post('/user/{user}/save', ['as' => 'user.profil.save', 'uses' => 'MySpaceController@saveUserProfil']);
    
});

Route::get('/user/{user}', ['as' => 'user.profil.index', 'uses' => 'MySpaceController@userProfil']);

Route::get('socialCounts', 'FrontController@socialCounts');
Route::get('/', ['as' => 'front.index', 'uses' => 'FrontController@index']);



Route::group(array('before' => 'cache', 'after' => 'cache'), function()
{
    Route::get('/manga/{manga}/{chapter}/{page?}', ['as' => 'front.manga.reader', 'uses' => 'ReaderController@reader'])
        ->where('page', '^[1-9][0-9]*');
});

Route::get('/manga/{manga}', ['as' => 'front.manga.show', 'uses' => 'FrontController@show']);
Route::get('/news/{post}', ['as' => 'front.news', 'uses' => 'FrontController@news']);
Route::get('/latest-release', ['as' => 'front.manga.latestRelease', 'uses' => 'FrontController@latestRelease']);
Route::get('/latest-news', ['as' => 'front.manga.latestNews', 'uses' => 'FrontController@latestNews']);
Route::get('/random', ['as' => 'front.manga.random', 'uses' => 'FrontController@randomManga']);
Route::get('/contact-us', ['as' => 'front.manga.contactUs', 'uses' => 'FrontController@contactUs']);
Route::post('/contact-us', ['as' => 'front.manga.sendMessage', 'uses' => 'FrontController@sendMessage']);
Route::post('/report-bug', ['as' => 'front.manga.reportBug', 'uses' => 'ReaderController@reportBug']);
Route::get('search', 'FrontController@search');

Route::get('filter', 'FrontController@filter');
Route::get('filterList', 'FrontController@filterList');
Route::get('changeMangaList', 'FrontController@changeMangaList');
Route::get('/manga-list/{type?}/{archive?}', ['as' => 'front.manga.list', 'uses' => 'FrontController@mangalist']);
Route::get('/manga-list', ['as' => 'front.manga.list', 'uses' => 'FrontController@mangalist']);

Route::get('/install', ['as' => 'install.index', 'uses' => 'InstallerController@index']);
Route::post('startInstall', 'InstallerController@startInstall');

Route::get('/robots.txt', 'FrontController@robots');
Route::get('/sitemap.xml', 'FrontController@sitemap');
Route::get('/feed', 'FrontController@feed');

Route::when('manga/*', 'manga.view_throttle');

Route::get('/download/{mangaSlug}/{chapterId}', ['as' => 'front.manga.download', 'uses' => 'FrontController@downloadChapter']);

Route::get('/advanced-search', ['as' => 'front.advSearch', 'uses' => 'FrontController@advSearch']);
Route::post('advSearchFilter', 'FrontController@advSearchFilter');

// comment
Route::get('/api/comments/{type}/{id}', ['as' => 'api.comments.index', 'uses' => 'CommentController@index']);
Route::group(array('prefix' => 'api'), function() {
    Route::resource('comments', 'CommentController', array('except' => array('create', 'edit', 'update')));
});

app/models/Role.php
<?php

use Zizaco\Entrust\EntrustRole;

/**
 * Page Model Class
 * 
 * PHP version 5.4
 *
 * @category PHP
 * @package  Controller
 * @author   cyberziko <cyberziko@gmail.com>
 * @license  commercial http://getcyberworks.com/
 * @link     http://getcyberworks.com/
 */
class Role extends EntrustRole
{
	public $fillable = ['name'];
    public static $rules = ['name' => 'required|unique:roles,name,:id'];
	public $errors;
	
	/**
     * Validate chapter
     * 
     * @param type $mangaid manga id
     * 
     * @return boolean
     */
    public function isValid()
    {
    	static::$rules = str_replace(':id', $this->id, static::$rules);
		
        $validation = Validator::make($this->attributes, static::$rules);

        if ($validation->passes()) {
            return true;
        }

        $this->errors = $validation->messages();
        return false;
    }
}

app/models/User.php
<?php

use Illuminate\Auth\UserTrait;
use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableTrait;
use Illuminate\Auth\Reminders\RemindableInterface;
use Zizaco\Entrust\HasRole;
use Zizaco\Confide\ConfideUser;
use Zizaco\Confide\ConfideUserInterface;

/**
 * User Model Class
 * 
 * PHP version 5.4
 *
 * @category PHP
 * @package  Controller
 * @author   cyberziko <cyberziko@gmail.com>
 * @license  commercial http://getcyberworks.com/
 * @link     http://getcyberworks.com/
 */
class User extends Eloquent implements UserInterface, RemindableInterface,
        ConfideUserInterface
{

    use ConfideUser;
    use HasRole;

    public $fillable = ['name', 'username', 'password', 'email', 'confirmed'];
	
    public function manga()
    {
        return $this->hasMany('Manga')->orderBy('slug', 'desc');
    }
	
	public function chapters()
    {
        return $this->hasMany('Chapter')->orderBy('slug', 'desc');
    }
}

app/controllers/RoleController.php
<?php

/**
 * Role Controller Class
 * 
 * PHP version 5.4
 *
 * @category PHP
 * @package  Controller
 * @author   cyberziko <cyberziko@gmail.com>
 * @license  commercial http://getcyberworks.com/
 * @link     http://getcyberworks.com/
 */
class RoleController extends BaseController
{

    protected $role;

    /**
     * Constructor
     * 
     * @param Chapter $chapter current chapter
     */
    public function __construct(Role $role)
    {
        $this->role = $role;
    }

    /**
     * Load Manga page
     * 
     * @return manga page
     */
    public function index()
    {
    	$roles = Role::all();
		
        return View::make(
            'admin.users.role.index',
            ['roles' => $roles]
        );
    }

    /**
     * Load Manga chapter create page
     *  
     * @return view
     */
    public function create()
    {
    	$permissions = Permission::all();
		
        return View::make(
            'admin.users.role.create', 
            ['permissions' => $permissions]
        );
    }

    /**
     * Edit page
     * 
     * @param type $id identifier
     * 
     * @return view
     */
    public function edit($id)
    {
    	$role = Role::find($id);
        $permissions = Permission::all();

        if(count($role->perms)>0){
            foreach ($role->perms as $perm) {
                foreach ($permissions as $key=>$permission) {
                    if($permission->id === $perm->id) {
                        unset($permissions[$key]);
                    }
                }
            }
	}
				
        return View::make(
            'admin.users.role.edit',
            [
            	'permissions' => $permissions,
                'role' => $role,
            ]
        );
    }
	
    /**
     * Save the new chapter
     * 
     * @return detail page
     */
    public function store()
    {
        $inputs = Input::all();
        $role = new Role();

        if (!$role->fill($inputs)->isValid()) {
            return Redirect::back()->withInput()->withErrors($role->errors);
        }
		
        $role->save();

        $permsList = $inputs['perms'];
        $perms = explode(",", $permsList);

        if (count($perms)>=1 && $perms[0] != "") {
            $role->perms()->sync($perms);	 
        }

        return Redirect::route('admin.role.index')
            ->with('createSuccess', Lang::get('messages.admin.users.role.create-success'));;
    }

    /**
     * Load Manga chapter edit page
     * 
     * @param type $mangaId   manga identifier
     * @param type $chapterId chapter identifier
     * 
     * @return edit page with message
     */
    public function update($id)
    {
        $inputs = Input::all();
        $role = Role::find($id);

        if (!$role->fill($inputs)->isValid()) {
            return Redirect::back()->withInput()->withErrors($role->errors);
        }

        $permsList = $inputs['perms'];
        $perms = explode(",", $permsList);

        if (count($perms)==1 && $perms[0] == "") {
            $role->perms()->detach();	 
        } else {
            $role->perms()->sync($perms);	 
        }

        $role->save();

        return Redirect::back()
            ->with('updateSuccess', Lang::get('messages.admin.users.role.update-success'));
    }

    /**
     * Delete chapter
     * 
     * @param type $mangaId   manga identifier
     * @param type $chapterId chapter identifier
     * 
     * @return view
     */
    public function destroy($id)
    {
        $role = Role::find($id);

        $role->delete();

        return Redirect::route('admin.role.index');
    }

}

app/views/admin/users/role/create.blade.php
@extends('admin.layouts.default')

@section('breadcrumbs', Breadcrumbs::render())

@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-plus-square-o fa-fw"></i> {{ Lang::get('messages.admin.users.roles.create') }}
                <div class="pull-right">
                    {{ link_to_route('admin.role.index', Lang::get('messages.admin.manga.back'), null, array('class' => 'btn btn-default btn-xs', 'role' => 'button')) }}
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">

                {{ Form::open(array('route' => 'admin.role.store')) }}
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            {{Form::label('name', Lang::get('messages.admin.users.roles.role-name'))}}
                            {{Form::text('name', '', array('class' => 'form-control'))}}
                            {{ $errors->first('name', '<label class="error" for="name">:message</label>') }}
                        </div>
                    </div>
                </div>

                <br/>

                <label>{{ Lang::get('messages.admin.users.roles.select-perms') }}</label>
                <div class="row">
                    <div class="col-sm-4 col-sm-offset-1">
                        <div class="list-group" id="list1">
                            <div class="list-group-item active">
                                {{ Lang::get('messages.admin.users.permissions') }}
                                <input title="toggle all" class="all pull-right" type="checkbox">
                            </div>
                            @if(count($permissions)>0)
                            @foreach ($permissions as $permission)
                            <div class="list-group-item" data-id="{{ $permission->id }}">
                                {{ $permission->display_name }}
                                <input class="pull-right" type="checkbox">
                            </div>
                            @endforeach
                            @endif
                        </div>
                    </div>
                    <div class="col-sm-2 v-center">
                        <div title="Send to list 2" class="btn btn-default center-block add">
                            <i class="glyphicon glyphicon-chevron-right"></i>
                        </div>
                        <div title="Send to list 1" class="btn btn-default center-block remove">
                            <i class="glyphicon glyphicon-chevron-left"></i>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="list-group" id="list2">
                            <div class="list-group-item active">
                                {{ Lang::get('messages.admin.users.roles.role-perms') }}
                                <input title="toggle all" class="all pull-right" type="checkbox">
                            </div>

                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        {{ Form::submit(Lang::get('messages.admin.settings.save'), array('class' => 'btn btn-primary center-block save', 'style' => 'width: 100%')) }}
                    </div>
                </div>
                {{ Form::hidden('perms', '', array('id' => 'perms')) }}
                {{ Form::close() }}
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>

<script>
    function updatePerms() {
        var perms = Array();
        $("#list2 .list-group-item").each(function (idx, item) {
            id = $(item).attr('data-id');
            if (id !== undefined)
                perms.push($(item).attr('data-id'));
        });

        $('#perms').val(perms);
    }

    updatePerms();

    $('.add').click(function () {
        $('.all').prop("checked", false);
        var items = $("#list1 input:checked:not('.all')");
        var n = items.length;
        if (n > 0) {
            items.each(function (idx, item) {
                var choice = $(item);
                choice.prop("checked", false);
                choice.parent().appendTo("#list2");
            });

            updatePerms();
        } else {
            alert("Choose an item from list 1");
        }
    });

    $('.remove').click(function () {
        $('.all').prop("checked", false);
        var items = $("#list2 input:checked:not('.all')");
        items.each(function (idx, item) {
            var choice = $(item);
            choice.prop("checked", false);
            choice.parent().appendTo("#list1");
        });

        updatePerms();
    });

    /* toggle all checkboxes in group */
    $('.all').click(function (e) {
        e.stopPropagation();
        var $this = $(this);
        if ($this.is(":checked")) {
            $this.parents('.list-group').find("[type=checkbox]").prop("checked", true);
        } else {
            $this.parents('.list-group').find("[type=checkbox]").prop("checked", false);
            $this.prop("checked", false);
        }
    });

    $('[type=checkbox]').click(function (e) {
        e.stopPropagation();
    });

    /* toggle checkbox when list group item is clicked */
    $('.list-group a').click(function (e) {

        e.stopPropagation();

        var $this = $(this).find("[type=checkbox]");
        if ($this.is(":checked")) {
            $this.prop("checked", false);
        } else {
            $this.prop("checked", true);
        }

        if ($this.hasClass("all")) {
            $this.trigger('click');
        }
    });
</script>
@stop

app/views/admin/users/role/edit.blade.php
@extends('admin.layouts.default')

@section('breadcrumbs', Breadcrumbs::render())

@section('content')
<div class="row">
    <div class="col-lg-12">
        @if (Session::has('updateSuccess'))
        <div class="alert text-center alert-info ">
            {{ Session::get('updateSuccess') }}
        </div>
        @endif

        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-pencil-square-o fa-fw"></i> {{ Lang::get('messages.admin.users.roles.edit') }}
                <div class="pull-right">
                    {{ link_to_route('admin.role.index', Lang::get('messages.admin.manga.back'), null, array('class' => 'btn btn-default btn-xs', 'role' => 'button')) }}
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">

                {{ Form::open(array('route' => array('admin.role.update', $role->id), 'method' => 'PUT')) }}
                @if($role->name !== 'Admin')
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            {{Form::label('name', Lang::get('messages.admin.users.roles.role-name'))}}
                            {{Form::text('name', $role->name, array('class' => 'form-control'))}}
                            {{ $errors->first('name', '<label class="error" for="name">:message</label>') }}
                        </div>
                    </div>
                </div>
                <br/>
                @endif

                <label>{{ Lang::get('messages.admin.users.roles.select-perms') }}</label>
                <div class="row">
                    <div class="col-sm-4 col-sm-offset-1">
                        <div class="list-group" id="list1">
                            <div class="list-group-item active">
                                {{ Lang::get('messages.admin.users.permissions') }}
                                <input title="toggle all" class="all pull-right" type="checkbox">
                            </div>
                            @if(count($permissions)>0)
                            @foreach ($permissions as $permission)
                            <div class="list-group-item" data-id="{{ $permission->id }}">
                                {{ $permission->display_name }}
                                <input class="pull-right" type="checkbox">
                            </div>
                            @endforeach
                            @endif
                        </div>
                    </div>
                    <div class="col-sm-2 v-center">
                        <div title="Send to list 2" class="btn btn-default center-block add">
                            <i class="glyphicon glyphicon-chevron-right"></i>
                        </div>
                        <div title="Send to list 1" class="btn btn-default center-block remove">
                            <i class="glyphicon glyphicon-chevron-left"></i>
                        </div>
                    </div>
                    <div class="col-sm-4">
                        <div class="list-group" id="list2">
                            <div class="list-group-item active">
                                {{ Lang::get('messages.admin.users.roles.role-perms') }}
                                <input title="toggle all" class="all pull-right" type="checkbox">
                            </div>
                            @if(count($role->perms)>0)
                            @foreach ($role->perms as $permission)
                            <div class="list-group-item" data-id="{{ $permission->id }}">
                                {{ $permission->display_name }}
                                <input class="pull-right" type="checkbox">
                            </div>
                            @endforeach
                            @endif
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-sm-4">
                        {{ Form::submit(Lang::get('messages.admin.settings.update'), array('class' => 'btn btn-primary center-block save', 'style' => 'width: 100%')) }}
                    </div>
                </div>
                {{ Form::hidden('perms', '', array('id' => 'perms')) }}
                {{ Form::close() }}
            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>

<script>
    function updatePerms() {
        var perms = Array();
        $("#list2 .list-group-item").each(function (idx, item) {
            id = $(item).attr('data-id');
            if (id !== undefined)
                perms.push($(item).attr('data-id'));
        });

        $('#perms').val(perms);
    }

    updatePerms();

    $('.add').click(function () {
        $('.all').prop("checked", false);
        var items = $("#list1 input:checked:not('.all')");
        var n = items.length;
        if (n > 0) {
            items.each(function (idx, item) {
                var choice = $(item);
                choice.prop("checked", false);
                choice.parent().appendTo("#list2");
            });

            updatePerms();
        } else {
            alert("Choose an item from list 1");
        }
    });

    $('.remove').click(function () {
        $('.all').prop("checked", false);
        var items = $("#list2 input:checked:not('.all')");
        items.each(function (idx, item) {
            var choice = $(item);
            choice.prop("checked", false);
            choice.parent().appendTo("#list1");
        });

        updatePerms();
    });

    /* toggle all checkboxes in group */
    $('.all').click(function (e) {
        e.stopPropagation();
        var $this = $(this);
        if ($this.is(":checked")) {
            $this.parents('.list-group').find("[type=checkbox]").prop("checked", true);
        } else {
            $this.parents('.list-group').find("[type=checkbox]").prop("checked", false);
            $this.prop("checked", false);
        }
    });

    $('[type=checkbox]').click(function (e) {
        e.stopPropagation();
    });

    /* toggle checkbox when list group item is clicked */
    $('.list-group a').click(function (e) {

        e.stopPropagation();

        var $this = $(this).find("[type=checkbox]");
        if ($this.is(":checked")) {
            $this.prop("checked", false);
        } else {
            $this.prop("checked", true);
        }

        if ($this.hasClass("all")) {
            $this.trigger('click');
        }
    });
</script>
@stop

app/views/admin/users/role/index.blade.php
@extends('admin.layouts.default')

@section('breadcrumbs', Breadcrumbs::render())

@section('content')
<div class="row">
    <div class="col-lg-12">
        @if (Session::has('createSuccess'))
        <div class="alert text-center alert-info ">
            {{ Session::get('createSuccess') }}
        </div>
        @endif

        <div class="panel panel-default">
            <div class="panel-heading">
                <i class="fa fa-bars fa-fw"></i> {{ Lang::get('messages.admin.users.roles') }}
                <div class="pull-right">
                    {{ link_to_route('admin.role.create', Lang::get('messages.admin.users.roles.add'), null, array('class' => 'btn btn-primary btn-xs pull-right', 'role' => 'button')) }}
                </div>
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th style="min-width: 200px;">{{ Lang::get('messages.admin.users.roles.role') }}</th>
                                        <th>{{ Lang::get('messages.admin.users.permissions') }}</th>
                                        <th style="min-width: 200px;"></th>
                                    </tr>
                                </thead>
                                @foreach($roles as $role)
                                <tr>
                                    <td>{{ $role->name }}</td>
                                    <td>{{ App::make("HelperController")->listAsString($role->perms, ', ') }}</td>
                                    <td style="text-align: right;"> {{ link_to_route('admin.role.edit', Lang::get('messages.admin.users.edit'), $role->id, array('class' => 'btn btn-primary btn-xs')); }}
                                        <div style="display: inline-block">
                                            {{ Form::open(array('route' => array('admin.role.destroy', $role->id), 'method' => 'delete')) }}
                                            {{ Form::submit(Lang::get('messages.admin.users.delete') , array('class' => 'btn btn-danger btn-xs',  'onclick' => 'if (!confirm("'.Lang::get('messages.admin.users.roles.confirm-delete').'")) {return false;}')) }}
                                            {{ Form::close() }}
                                        </div></td>
                                </tr>
                                @endforeach
                            </table>
                        </div>
                    </div>
                </div>

            </div>
            <!-- /.panel-body -->
        </div>
    </div>
</div>
@stop